### ISSUE TITLE
getUser() dont work when nooone is logged in

### ISSUE THREAD

**Issue by Henderxx** [profanis/codeShotsWithProfanis#1]
after moving token from constructor and setting geter and getUser function, browser does not show anything on page and in console is error with getUser() function in auth service

![image](https://user-images.githubusercontent.com/46646181/141328738-32fd6251-3144-46ca-8ab2-2f5b1c2727e4.png)

https://rlmizqrmr.github.stackblitz.io

**Comment by profanis** [comment]
Unfortunately, I can not open the stackblitz link

**Comment by Henderxx** [comment]
mabe i posted wrong link, try this one
https://stackblitz.com/github/profanis/codeShotsWithProfanis/tree/21/auth-login-has-role-guard

**Comment by profanis** [comment]
ohh yeah! 

Just saw it. It seems that I missed checking if the `token` exists before trying to parse it.

If you add the following in the `auth.service.ts`, would work

```ts
  private getUser(token: string): UserModel {
    if (!token) {
      return null
    }
    return JSON.parse(atob(token.split('.')[1])) as UserModel;
  }
```

**Comment by Henderxx** [comment]
I knew it was checking existence of token but i tried to do this in wrong place ( in constructor). This would probably help but null can't be assigned to UserModel type

**Comment by profanis** [comment]
> I knew it was checking existence of token but i tried to do this in wrong place ( in constructor). This would probably help but null can't be assigned to UserModel type

In a production code, I would have converted the UserModel to a nullable one.
Requires some more tweaks and it would work great.

**Comment by Henderxx** [comment]
i think i got it to work. edited User Model to be nullable (i hope this is proper way to do this)

```ts
export interface UserModel {
  username?: string | null;
  firstName?: string | null;
  roles?: string[] | null;
}
```
added null option to getUser method

```ts
private getUser(token: string): UserModel | null {
    if (!token) {
      return null;
    }
    return JSON.parse(atob(token.split('.')[1])) as UserModel;
  }
```

and i had to add ` "strictNullChecks": false,` to tsconfig.json

somehow it's working

**Comment by profanis** [comment]
I wouldn't vote to opt-out the `strictNullChecks`.

Have a look at this commit https://github.com/profanis/codeShotsWithProfanis/commit/6e7a70b2b7d68c922d43cf4e74095e1076e32ff1

**Comment by Henderxx** [comment]
ahh, almost had it. Btw disabled `strictNullChecks` in tsconfig is working not for one service but whole application ?

**Comment by profanis** [comment]
> ahh, almost had it. Btw disabled `strictNullChecks` in tsconfig is working not for one service but whole application ?

Yes, it is a setting that affects the whole application.

**Comment by profanis** [comment]
@Henderxx Thanks a lot for pointing out this error!

**Comment by Henderxx** [comment]
No problem, thank you for help. One more question about http interceptors, they also work for every request right? because with fake backend it works now but when i use external backend i got error again when reading lenght of token while loging. when i removed auth-interceptors it works so i added `headers: request.headers.set('authorization', this.authService.token || '')` and its working as well

**Comment by profanis** [comment]
Yes, the HTTP interceptor works on every HTTP request
